<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="13.0.2" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>0855504d-cd14-4615-a82d-e6209589f9f1</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.Keycloak" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Passistant.Common\Passistant.Common.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="..\Passistant.MealPlanner\Passistant.MealPlanner.csproj" />
  </ItemGroup>

</Project>
